spring:
  application:
    name: tlias-web

  datasource:
    url: jdbc:mysql://47.108.201.216:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tlias
    password: hzzhxp131421
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.huangzizhu.pojo
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucketName: huangzizhu-java-web
    region: cn-chengdu

ssh:
  cfg:
    is-on: false
    ssh-user: root
    ssh-password: BT-Panel-sjhu
    local-port: 3307
    remote-port: 3306
    ssh-host: 47.108.201.216
    ssh-port: 22
