CREATE TABLE `song` (
                        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '歌曲ID（唯一标识）',
                        `name` VARCHAR(255) NOT NULL COMMENT '歌曲名称',
                        `artist` VARCHAR(255)  COMMENT '歌手/艺术家',
                        `album_id` BIGINT UNSIGNED NOT NULL COMMENT '专辑ID（逻辑外键）',
                        `album_name` VARCHAR(255)  COMMENT '专辑（逻辑外键）',
                        `year` VARCHAR(10) NULL COMMENT '发行年份',
                        `duration` INT UNSIGNED NOT NULL COMMENT '时长（秒）',
                        `format` VARCHAR(50) NOT NULL COMMENT '音频格式（如MP3、WAV等）',
                        `size` BIGINT UNSIGNED NOT NULL COMMENT '文件大小（字节）',
                        `cover_url` VARCHAR(255) NULL DEFAULT '' COMMENT '封面图片URL',
                        `bit_rate` INT UNSIGNED NULL COMMENT '比特率（kbps）',
                        `sample_rate` INT UNSIGNED NULL COMMENT '采样率（Hz）',
                        `path` VARCHAR(255) NOT NULL COMMENT '存储路径',
                        `md5` CHAR(32) NOT NULL COMMENT '文件的MD5值，用于唯一标识',
                        `is_available` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可用（1表示可用，0表示不可用）',
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `unique_md5` (`md5`) COMMENT 'MD5值唯一索引',
                        INDEX `idx_md5` (`md5`) COMMENT 'MD5值索引，优化查询'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='歌曲表';